# Generated by Django 4.2.11 on 2026-04-29 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_ping', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active_session', models.BooleanField(default=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracking_work_session',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tracking_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracking_user_profile',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('offline', 'Offline')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tracking.worksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracking_activity_log',
            },
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['user', 'is_active_session'], name='tracking_wo_user_id_0b36bb_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['user', 'login_time'], name='tracking_wo_user_id_4378c9_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['last_ping'], name='tracking_wo_last_pi_c91d35_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['login_time'], name='tracking_wo_login_t_ce6ca6_idx'),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active_session', True)), fields=('user',), name='only_one_active_session_per_user'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='tracking_us_user_id_bed834_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_tracking_enabled'], name='tracking_us_is_trac_b9a8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='tracking_ac_user_id_596ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['session', 'timestamp'], name='tracking_ac_session_e1c6aa_idx'),
        ),
    ]
