# Generated by Django 4.2.11 on 2026-05-20 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='screenshots_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tracking/screenshots/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_idle', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='tracking.worksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracking_screenshot',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='tracking_sc_user_id_4f52bd_idx'), models.Index(fields=['session', 'timestamp'], name='tracking_sc_session_0f09b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('window_title', models.CharField(blank=True, max_length=500)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_productive', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_activities', to='tracking.worksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'App Activities',
                'db_table': 'tracking_app_activity',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='tracking_ap_user_id_821b54_idx'), models.Index(fields=['session', 'timestamp'], name='tracking_ap_session_f3072a_idx'), models.Index(fields=['app_name'], name='tracking_ap_app_nam_7dfb43_idx')],
            },
        ),
    ]
