# Generated by Django 6.0.2 on 2026-05-20 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_userprofile_screenshots_enabled_screenshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='is_desktop_idle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worksession',
            name='last_desktop_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['last_desktop_ping'], name='tracking_wo_last_de_4657db_idx'),
        ),
    ]
