# Generated by Django 4.2.11 on 2026-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_worksession_is_desktop_idle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appactivity',
            name='key_presses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appactivity',
            name='mouse_moves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appactivity',
            name='productive_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='activity_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='key_presses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='mouse_moves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='productive_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
