# Generated by Django 4.2.11 on 2026-05-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_appactivity_key_presses_appactivity_mouse_moves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='break_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='idle_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
