# Generated by Django 6.0.2 on 2026-05-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_worksession_break_count_worksession_idle_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='appactivity',
            name='productive_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='tracked_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
