# Generated by Django 6.0.2 on 2026-05-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_appactivity_productive_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appactivity',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
