# Generated by Django 4.2.11 on 2026-05-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_appactivity_clicks_worksession_clicks'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worksession',
            name='only_one_active_session_per_user',
        ),
        migrations.AddField(
            model_name='worksession',
            name='device_id',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='worksession',
            name='installation_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='machine_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='tracker_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active_session', True)), fields=('user', 'device_id'), name='only_one_active_session_per_user_device'),
        ),
    ]
