# Generated by Django 6.0.2 on 2026-03-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectmember_unique_together_and_more'),
        ('proposals', '0002_proposal_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_projects', to='projects.project'),
        ),
    ]
