# Generated by Django 6.0.2 on 2026-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposal_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
