# Generated by Django 4.2.11 on 2026-06-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposal_is_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='builder_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
