# Generated by Django 6.0.2 on 2026-03-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='email_sent_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='email_sent_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='email_sent_today',
            field=models.BooleanField(default=False),
        ),
    ]
