# Generated by Django 6.0.2 on 2026-03-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_options_reminder_email_sent_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='email_sent_created',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='email_sent_overdue',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='email_sent_today',
        ),
    ]
