# Generated by Django 4.2.11 on 2026-04-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_remove_reminder_email_sent_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email_sent_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='email_sent_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
