# Generated by Django 6.0.2 on 2026-03-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('module', models.CharField(choices=[('reminder', 'Reminder'), ('domain', 'Domain'), ('invoice', 'Invoice')], max_length=50)),
                ('type', models.CharField(choices=[('REMINDER_DUE', 'Reminder Due'), ('REMINDER_OVERDUE', 'Reminder Overdue'), ('DOMAIN_EXPIRING', 'Domain Expiring'), ('DOMAIN_EXPIRED', 'Domain Expired'), ('INVOICE_DUE', 'Invoice Due')], max_length=50)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
