# Generated by Django 6.0.2 on 2026-03-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
