# Generated by Django 6.0.2 on 2026-07-10 11:12

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_client_user_profile_photo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.SoftDeleteUserManager()),
            ],
        ),
    ]
