# Generated by Django on 2026-03-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.TextField(blank=True, default="")),
                ("position", models.CharField(max_length=120)),
                ("joining_date", models.DateField()),
                ("salary_monthly", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.department")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="employee", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="HRDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("doc_type", models.CharField(choices=[("offer_letter", "Offer Letter"), ("appraisal_letter", "Appraisal Letter"), ("experience_certificate", "Experience Certificate"), ("salary_certificate", "Salary Certificate")], max_length=40)),
                ("issued_on", models.DateField(default=now)),
                ("payload", models.JSONField(default=dict)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="hr_documents/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="generated_hr_documents", to=settings.AUTH_USER_MODEL)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="hr_documents.employee")),
            ],
        ),
    ]

