# Generated by Django 6.0.2 on 2026-02-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='file',
            field=models.FileField(default=None, upload_to='task_files/'),
            preserve_default=False,
        ),
    ]
