# Generated by Django 6.0.2 on 2026-03-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_taskfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['-id']},
        ),
    ]
