# Generated by Django 6.0.2 on 2026-03-12 10:50

import apps.infrastructure.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_projectmember_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('server_ip', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='projects.project')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='infrastructure.server')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_url', models.URLField(blank=True, max_length=500)),
                ('admin_username', models.CharField(blank=True, max_length=255)),
                ('admin_password', apps.infrastructure.models.EncryptedTextField(blank=True)),
                ('cpanel_url', models.URLField(blank=True, max_length=500)),
                ('cpanel_username', models.CharField(blank=True, max_length=255)),
                ('cpanel_password', apps.infrastructure.models.EncryptedTextField(blank=True)),
                ('ftp_host', models.CharField(blank=True, max_length=255)),
                ('ftp_username', models.CharField(blank=True, max_length=255)),
                ('ftp_password', apps.infrastructure.models.EncryptedTextField(blank=True)),
                ('contact_form_email', models.EmailField(blank=True, max_length=254)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_email_password', apps.infrastructure.models.EncryptedTextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='infrastructure.domain')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='projects.project')),
            ],
        ),
    ]
