# Generated by Django 6.0.2 on 2026-03-24 09:19

import apps.infrastructure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_domain_created_at_server_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecredential',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='websitecredential',
            name='business_email_password',
            field=apps.infrastructure.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecredential',
            name='business_email_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
