# Generated by Django 6.0.2 on 2026-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_websitecredential_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='alert_1_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='alert_30_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='alert_7_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='alert_expired_sent',
            field=models.BooleanField(default=False),
        ),
    ]
