# Generated by Django 6.0.2 on 2026-03-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_domain_alert_1_sent_domain_alert_30_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='alert_1_sent',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='alert_30_sent',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='alert_7_sent',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='alert_expired_sent',
        ),
    ]
