# Generated by Django 6.0.2 on 2026-03-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-id']},
        ),
    ]
