# Generated by Django 6.0.2 on 2026-04-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_lead_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='competitor_websites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contacted_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='details_given',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='documents_given',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='enquiry_from',
            field=models.CharField(blank=True, choices=[('WhatsApp', 'WhatsApp'), ('Call', 'Call'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='how_contacted',
            field=models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Reference', 'Reference'), ('Friend', 'Friend')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='login_credentials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='reference_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_required',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
