# Generated by Django 6.0.2 on 2026-03-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoiceitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
