# Generated by Django 6.0.2 on 2026-03-16 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_projectmember_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='projects.client')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broken_links', models.IntegerField(default=0)),
                ('sitemap_updated', models.BooleanField(default=True)),
                ('lcp', models.FloatField()),
                ('cls', models.FloatField()),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seo.website')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
                ('reach', models.IntegerField()),
                ('last_update', models.DateField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.website')),
            ],
        ),
        migrations.CreateModel(
            name='SEOTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('ON_PAGE', 'On Page'), ('KEYWORD', 'Keyword'), ('TECHNICAL', 'Technical'), ('BACKLINK', 'Backlink')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.client')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_tasks', to='seo.website')),
            ],
        ),
        migrations.CreateModel(
            name='SEOAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('traffic', models.IntegerField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.website')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('search_volume', models.IntegerField()),
                ('difficulty', models.FloatField()),
                ('rank', models.IntegerField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.website')),
            ],
        ),
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('domain_authority', models.IntegerField()),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('REMOVED', 'Removed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.website')),
            ],
        ),
    ]
