# Generated by Django 4.2.11 on 2026-06-08 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_alter_client_options_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seo_activity_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SEODailyWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='seo_proofs/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('remarks_by_manager', models.TextField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_seo_logs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_seo_logs', to=settings.AUTH_USER_MODEL)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_daily_logs', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_seo_logs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_seo_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seo_daily_work_log',
                'ordering': ['-log_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=255)),
                ('domain_url', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('package_plan', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('custom', 'Custom')], default='basic', max_length=50)),
                ('google_search_console_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sitemap_url', models.URLField(blank=True, null=True)),
                ('target_country', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_seo_websites_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_seo_websites', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_websites', to='projects.client')),
            ],
            options={
                'db_table': 'seo_website',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_seo_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_seo_tasks', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_tasks', to='seo.website')),
            ],
            options={
                'db_table': 'seo_task',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_seo_reminders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_seo_reminders', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_reminders', to='seo.website')),
            ],
            options={
                'db_table': 'seo_reminder',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOMonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('target_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_targets', to='seo.seoactivitytype')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_targets', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_targets', to='seo.website')),
            ],
            options={
                'db_table': 'seo_monthly_target',
                'ordering': ['-month', 'executive'],
            },
        ),
        migrations.CreateModel(
            name='SEODailyWorkLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_url', models.TextField(blank=True, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_items', to='seo.seoactivitytype')),
                ('work_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seo.seodailyworklog')),
            ],
            options={
                'db_table': 'seo_daily_work_log_item',
            },
        ),
        migrations.AddField(
            model_name='seodailyworklog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='seo.website'),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('search_volume', models.IntegerField(default=0)),
                ('difficulty_score', models.FloatField(default=0.0)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('target_rank', models.IntegerField(blank=True, null=True)),
                ('current_rank', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_keywords', to='seo.website')),
            ],
            options={
                'db_table': 'seo_keyword',
                'ordering': ['keyword'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='seodailyworklog',
            unique_together={('executive', 'website', 'log_date')},
        ),
    ]
