# Generated by Django 6.0.2 on 2026-03-16 05:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectmember_unique_together_and_more'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='google_search_console_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='sitemap_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_websites', to='projects.client'),
        ),
    ]
