# Generated by Django 4.2.11 on 2026-06-08 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seodailyworklogitem',
            name='domain_authority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seodailyworklogitem',
            name='spam_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seodailyworklogitem',
            name='time_spent_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SEOCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_credentials', to='seo.website')),
            ],
            options={
                'db_table': 'seo_credential',
                'ordering': ['website', 'platform'],
            },
        ),
    ]
