# Generated by Django 4.2.11 on 2026-06-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_seodailyworklogitem_domain_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seodailyworklogitem',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seodailyworklogitem',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
