# Generated by Django 4.2.11 on 2026-06-08 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_seodailyworklogitem_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEODailyWorkProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_file', models.FileField(upload_to='seo_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_files', to='seo.seodailyworklog')),
            ],
            options={
                'db_table': 'seo_daily_work_proof',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
