# Generated by Django 6.0.2 on 2026-07-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_seed_seo_activities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seoactivitytype',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='seoactivitytype',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
