# Generated by Django 6.0.2 on 2026-07-11 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_alter_seoactivitytype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotask',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_tasks', to='seo.seoactivitytype'),
        ),
        migrations.AlterField(
            model_name='seotask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
