# Generated by Django 6.0.2 on 2026-07-13 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_seotask_activity_type_alter_seotask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seodailyworklog',
            name='seo_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to='seo.seotask'),
        ),
    ]
