# Generated by Django 6.0.2 on 2026-07-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_seodailyworklog_seo_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotask',
            name='manager_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seotask',
            name='review_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seotask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready_for_review', 'Ready for Review'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
