# Generated by Django 6.0.2 on 2026-07-13 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0009_seotask_manager_remarks_seotask_review_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOTaskTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='seo.seotask')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seo_task_timeline',
                'ordering': ['event_time'],
            },
        ),
    ]
